### ISSUE TITLE
News Search Form returns 404 &cHash empty

### ISSUE THREAD

**Issue by Tonyt8** [georgringer/news#2280] opened 2023-12-01 20:30 UTC
## Bug Report

**Current Behavior**
Using the News Search form: I enter a search term, click "start search". I receive a Page Not Found
The page did not exist or was inaccessible. Reason: Request parameters could not be validated (&cHash empty)

**Expected behavior/output**
To return a list of news items that use the word entered in the search term.

**Environment**
- TYPO3 version: 12.4.8
- news version: 11.2.0
- The Official TYPO3 Introduction Package
- bootstrap_package version: 14.0.7
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 11 and 10

**Possible Solution**
I have no idea

**Additional context**
I have tried using many different route enhancers options. I have not found anything to solve the issue.
With older versions of news and Typo3 with a similar set up as this I have used the news search form many time with success.
To test this issue I setup a clean Typo3 install.
Using Typo3 12.4.8 I setup an empty site.
Next: with extension manager, installed the The Official TYPO3 Introduction Package.
Next: with extension manager, installed the news extension. 
Only using the default language I added some news categories and news tags.
I added a few news items using the categories and tags I had previously made 
Set up some news pages and storage in the standard way.
List and detail pages work perfectly.
The human readable URL's work nicely.
I set up a news search page, to which I added the news search form plugin and the news search results plugin to the page.
I also tested by sending the search form results to a separate news search results page with the news search results plugin both version gave the same 404 Page Not Found.
I tried various route enhancers options.
I'm stuck and don't know what to try next.
Can you help?

Thanks.
Regards,
Tony

**Comment by zkrechowiec** [comment] 2024-01-02 14:24
Hi,
I also have the problem with version 11.3.0 of News
Have you found a fix?

Thanks,
Zoïa

**Comment by SventB** [comment] 2024-01-07 16:42
@Tonyt8 @zkrechowiec 
Problem is: News template uses method="get":
```
<n:searchForm object="{search}" name="search" pageUid="{settings.listPid}" method="get">
```
Just remove this attribute and method will be "post":
```
<n:searchForm object="{search}" name="search" pageUid="{settings.listPid}">
```
Caused by TYPO3 CMS setting
```
$GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFoundOnCHashError'] = true;
```

Also wrong in current version: https://github.com/georgringer/news/blob/main/Resources/Private/Templates/News/SearchForm.html#L12
FYI @georgringer

**Comment by crinis** [comment] 2024-01-30 10:32
@Tonyt8 @zkrechowiec 
TYPO3 throws that error when there is no cHash available AND the given GET-Parameters are not excluded from cHash comparison.

You could therefore set
` $GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'][] = '^tx_news_pi1[search]';`
in your extensions ext_localconf.php to exclude all parameters starting with above string from the cHash comparison. This should preserve parameters used for filtering results in the URL compared to using POST.

**Comment by Tonyt8** [comment] 2024-02-28 11:39
Hi SventB and Crinis,
To confirm the news search worked well after I followed your instructions. Thank you very much for your help. 
Tony

**Comment by einpraegsam** [comment] 2024-04-26 11:46
Same here for news 11.4.1 with TYPO3 12.4.10

**Comment by georgringer** [comment] 2024-11-03 18:58
should work now, therefore closing

**Closed by georgringer** 2024-11-03 18:58 UTC

**Comment by Hawkeye1909** [comment] 2024-11-08 15:25
@georgringer Could you elaborate on why it should work now, as I don't see either of the two suggested solutions being used in current main branch? I'm just curious...
