### ISSUE TITLE
News records are translated but not editable - JS error

### ISSUE THREAD

**Issue by niggoledde** [georgringer/news#2093] opened 2023-04-26 07:48 UTC
## Bug Report

**Current Behavior**
Translate a news record and try to edit it throws the following JS error and its not possible to edit the record. It freezes in loading.
_Uncaught (in promise) TypeError: Cannot set properties of null (setting 'disabled')
    at form-engine.js?bust=4054f497e6116bb98c9f4e397fb835254b06655c:13:12668
    at NodeList.forEach (<anonymous>)
    at Object.initializeLocalizationStateSelector (form-engine.js?bust=4054f497e6116bb98c9f4e397fb835254b06655c:13:12438)
    at Object.reinitialize (form-engine.js?bust=4054f497e6116bb98c9f4e397fb835254b06655c:13:12217)
    at form-engine.js?bust=4054f497e6116bb98c9f4e397fb835254b06655c:13:21565_

**Expected behavior/output**
Translate a news record and edit the record.

**Possible Solution**
Changing the TCA categories to the new TCA Type Category fixes the Problem.
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Feature-94622-NewTCATypeCategory.html

**Environment**
- TYPO3 version(s): 12.4.0
- news version: 11.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 10

**Comment by ic1011** [comment] 2023-06-27 21:28
I am experiencing the same issue.  Same version of the news extensions, same OS, same installation type, only the Typo3 version is 12.4.2 but the same issue was present in 12.4.0 as well.

Personally, I find it strange that the translation of folder records in Typo3 v12.4.2 is so counterintuitive (or maybe I'm doing something wrong) . In Typo3 v10 and below the process of localization of records was straightforward and similar to the localization of page content -  basically one had to add an "Alternative Page Language" record (which is missing in Typo3 v12.4.2). In Typo3 v12.4. one has to create a copy of the record (in this case news article) and then open it in edit mode, and then under the Language tab choose another language and eventually the parent record/news article. Why can't we just use the little country flag buttons that under normal circumstances would appear under the "Localize to" column in List view?

Sorry if I'm intruding and sorry if this is not the right place, but as I'm having the same issue and as the documentation of both Typo3 v12 and the news extension appears to be out of date, I thought I might as well share my frustration here and hope for the best :)

So please, I'll be very grateful if any of you guys could spare a tiny amount of your time and tell me if I'm doing something wrong or at least point me in the right direction.

**Comment by georgringer** [comment] 2023-06-28 10:49
hey, can you test with latest typo3 version, IMO I fixed that in the core

**Comment by ic1011** [comment] 2023-06-28 11:44
Hello!

@georgringer, I just did, assuming that there is no newer version of Typo3 than 12.4.2. Here are the steps I've taken:

1. Created a new news record.
2. Created a copy of the news record.
3. Edited the content of the copy and changed the language and chose a parent under the Language tab.
4. Clicked the Save button and got a loading screen and the following error in the console:

`Uncaught (in promise) TypeError: Cannot set properties of null (setting 'disabled')
    at form-engine.js:13:12668
    at NodeList.forEach (<anonymous>)
    at Object.initializeLocalizationStateSelector (form-engine.js:13:12438)
    at Object.reinitialize (form-engine.js:13:12217)
    at form-engine.js:13:21565
(anonymous) @ form-engine.js:13
initializeLocalizationStateSelector @ form-engine.js:13
reinitialize @ form-engine.js:13
(anonymous) @ form-engine.js:13
Promise.then (async)
initialize @ form-engine.js:13
(anonymous) @ java-script-item-processor.js:13
(anonymous) @ java-script-item-processor.js:13
(anonymous) @ java-script-item-processor.js:13
Promise.then (async)
executeJavaScriptModuleInstruction @ java-script-item-processor.js:13
javaScriptModuleInstruction @ java-script-item-processor.js:13
invoke @ java-script-item-processor.js:13
(anonymous) @ java-script-item-processor.js:13
processItems @ java-script-item-processor.js:13
(anonymous) @ java-script-item-handler.js?1686638365:13
Promise.then (async)
(anonymous) @ java-script-item-handler.js?1686638365:13
`
And now every time I try to edit the child news record I end up stuck with the same loading screen and error.

Thank you for finding a time to work on the issue and getting back to us.

**Comment by georgringer** [comment] 2023-06-29 19:22
ah thought https://review.typo3.org/c/Packages/TYPO3.CMS/+/79007 is merged. can you test the proposed change there?

**Comment by ic1011** [comment] 2023-06-30 12:49
Thank you for your patch!

I've applied the changes to the local instance and the issue is no more. When you do you think the patch will be merged and released?

**Comment by georgringer** [comment] 2023-06-30 17:20
I pinged some people, rebased the patch - maybe you wanna vote on the patch as well? closing the issue here as it is not a core issue

**Closed by georgringer** 2023-06-30 17:20 UTC
