### ISSUE TITLE
Speaking URL path segment eval

### ISSUE THREAD

**Issue by t3webman** [georgringer/news#1275] opened 2020-05-14 10:47 UTC
I saw that the path segment was an issue before because of doubles:
right now if you modify some content of the element it perceives the path segment as already existing and appends "-1" ...

after every modification that is saved, you must now clean the path segment and save again

**Comment by DavidBruchmann** [comment] 2020-05-14 11:55
related to or duplicate of #1274

**Comment by georgringer** [comment] 2020-05-15 13:19
Closed as core issue

**Closed by georgringer** 2020-05-15 13:19 UTC
