### ISSUE TITLE
Fatal error: Declaration of XclassedXliffParser::getParsedData() must be compatible

### ISSUE THREAD

**Issue by xerc** [georgringer/news#1030] opened 2019-08-29 14:26 UTC
fresh install of version 7.3 via _composer_ @ 8.7.27

```
Fatal error: Declaration of GeorgRinger\News\Xclass\XclassedXliffParser::getParsedData($sourcePath, $languageKey)
must be compatible with
TYPO3\CMS\Core\Localization\Parser\LocalizationParserInterface::getParsedData($sourcePath, $languageKey, $charset = '')
```

**Comment by georgringer** [comment] 2019-08-29 14:46
duplicate of #1027

**Closed by georgringer** 2019-08-29 14:46 UTC
