### ISSUE TITLE
Create a new tag in a non-saved news does not work

### ISSUE THREAD

**Issue by ayacoo** [georgringer/news#404] opened 2017-08-16 10:33 UTC
Tested with 5.3.3, 6.0 and master.

Scenario:
- BE User create a new newsentry. 
- Click on tab options
- In Tag Suggest box he set a new Tag and click on "Tag could not be found. Wanna create it? Click here!"

After that news return a alert box, because of an 500 error.

FormData:
item=Testnewsd33&newsid=0

web/typo3conf/ext/news/Classes/Hooks/SuggestReceiver.php doesn't handle news entries without an uid. I don't know if there is a possibillity to use the TYPO3 Core DataHandler and substNEWwithIDs.

Related code:
```
    public function queryTable(&$params, $recursionCounter = 0)
    {
        $uid = (int)GeneralUtility::_GP('uid');
```

**Comment by georgringer** [comment] 2018-03-31 12:14
duplicate of #184 (not yet fixed)

**Closed by georgringer** 2018-03-31 12:14 UTC
