### ISSUE TITLE
Background color of news modul icon is taken from staticfilecache module

### ISSUE THREAD

**Issue by mediaessenz** [georgringer/news#1801] opened 2022-06-12 20:55 UTC
## Bug Report

**Current Behavior**
The background color of the news modul icon is taken from the staticfilecache module.
![wrong-news-module-icon-color](https://user-images.githubusercontent.com/16038153/173253223-94537b44-4069-418b-bfb5-d2ac6943d85c.png)

**Expected behavior/output**
The background color should stay blue, like the origin module icon

**Environment**
- TYPO3 version(s): 10.4.28
- news version: 8.6.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: MacOS 12.4

**Possible Solution**
Use namespaced class names or move the style definitions to corresponding attributes, like the core icons.

**Comment by georgringer** [comment] 2022-06-13 07:37
can reproduce on latest news, can you test that?

**Comment by mediaessenz** [comment] 2022-06-13 11:12
The problem appears only, if I add a own module group with a module like so:
```php
        // Register jdcompetition backend module group
        ExtensionUtility::registerModule(
            'Jdcompetition',
            'jdcompetition',
            '',
            'after:web',
            [],
            [
                'access' => 'group',
                'icon' => 'EXT:jdcompetition/Resources/Public/Icons/BackendModules.svg',
                'labels' => 'LLL:EXT:jdcompetition/Resources/Private/Language/locallang_mod.xlf',
            ]
        );

        // Register users backend module
        ExtensionUtility::registerModule(
            'Jdcompetition',
            'jdcompetition',
            'users',
            'top',
            [
                BackendModuleController::class => 'users',
            ],
            [
                'access' => 'group',
                'icon' => 'EXT:jdcompetition/Resources/Public/Icons/FrontendUser.svg',
                'labels' => 'LLL:EXT:jdcompetition/Resources/Private/Language/locallang_mod_users.xlf',
                'navigationComponentId' => '',
                'inheritNavigationComponentFromMainModule' => false
            ]
        );

        // Register participants backend module
        ExtensionUtility::registerModule(
            'Jdcompetition',
            'jdcompetition',
            'participants',
            'after:users',
            [
                BackendModuleController::class => 'participants',
            ],
            [
                'access' => 'group',
                'icon' => 'EXT:jdcompetition/Resources/Public/Icons/Participant.svg',
                'labels' => 'LLL:EXT:jdcompetition/Resources/Private/Language/locallang_mod_participants.xlf',
                'navigationComponentId' => '',
                'inheritNavigationComponentFromMainModule' => false
            ]
        );
```
My svg icons are ok, they all use fill attributes for path definitions. I already tried to exchange them core icons, which does not make any different.
If I remove my module registration, the news modul icon becomes blue again.
The problem seems to be more a core or css problem in general.
But, if a svg icon uses fill attributes, like it is the case for all core icons, it doesn't appear.

**Comment by chesio** [comment] 2022-06-13 11:37
I believe the problem has been fixed with https://github.com/georgringer/news/commit/a1d143efe2d88430d77255e94ebe2501dfa60687. I cannot reproduce it with 9.4.0 (I can only reproduce it when I re-add the `class="cls-1"` to `path` element of the News module icon manually).

**Closed** 2022-06-13 13:03 UTC
Labels: Bug, Needs feedback from author

**Comment by mediaessenz** [comment] 2022-06-13 13:51
Sorry, but I do not realized, that this was already an issue.

After updating news to 9.4.0 the problem is solved.

**Comment by georgringer** [comment] 2022-06-13 15:32
thanks for rechecking latest version
