### ISSUE TITLE
A cache with identifier "news" does not exist.

### ISSUE THREAD

**Issue by foobar13372** [georgringer/news#869] opened 2019-03-15 10:13 UTC
#671 was closed. We had this problem on several projects as well. We could never make out any clear reason why this happens. It seems to happen as soon as one extends `ext:news` in some way, but happens not always. Or extension is loaded after `ext:news`. We are simply extending the model/repository via PHP and mapping our model to `tx_news_domain_model_news` via `ext_typoscript_setup.typoscript`. Nothing more, nothing less.

My knowledge about the cache managment from the TYPO3 core is to limited to be able to tell whether this is a news or a core problem, but we only ever had this problem with `ext:news`, never with any other extension (which we sometimes also extend).

This also just affects the install tool (DB compare and clear cache), the backend and frontend  itself are working (also the cache clear buttons in the top).

I already cleared all caches by hand (cf_* tables and typo3temp), problem stays. Can't tell what triggered it now (we were extending the models for quite some time, but the cache problem just appeared again for no obvious reason).

`ext:news` is version 7.1.0 but we already observed this for quite some time on otehr projets (6.x, maybe earlier).
TYPO3 is 8.7.24

**Comment by foobar13372** [comment] 2019-03-15 10:32
Additional Information, this seems to happen when the CacheManager is called from 
`EXT:ext/news/Classes/Utility/ClassLoader.php` -- so it seems indeed to be a problem from news, not from core.

**Comment by foobar13372** [comment] 2019-03-15 12:18
I found something else. We have another 3rd Party Extension (`ext:fs_media_gallery`) which has this in their ext_localconf:
`$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['classes']['Domain/Model/News'][] = $packageKey;`

What is strange because we have this Extension since "forever" and it had no updates for month. But if I comment out this line it suddently works again.

**Comment by foobar13372** [comment] 2019-03-18 07:09
I discussed this with some colleaques. It turned out that they know this behaviour, too. Often when one uses `$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['classes']['Domain/Model/News'][]` some install tool functions break with this Exception. The "hotfix" for them was to comment out this line wherever it appears, run the install tool function (DB compare modtly) and add the line again.

**Comment by georgringer** [comment] 2019-04-09 03:29
I don't have this issue since years. Please create an installation where I can reproduce that and have full access

**Comment by foobar13372** [comment] 2019-07-16 05:37
We just had this again on a project. We added
`$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['classes']['Domain/Model/News'][] = 'our_ext_key';` in `ext_localconf.php`. This worked as long as no 3rd party extension got an update with changed `ext_tables.sql`. But now there was an update. Our build failed failed, site went down, because the `typo3cms` console could not execute `database:update` because somehow this line blocked it. I had to fiddle around via SSH manually, because this line totally locks up the system when any changes afterwards on the SQL schema are needed (line blocks schema update -> site goes down as soon as any of the needed new columns are tried to be accessed).

**Comment by foobar13372** [comment] 2019-07-31 05:53
Just debugged this a bit more:
the line `$GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations']['news']  = [` is loaded from news' `ext_localconf` when entering the install tool. But when
`initializeCachingFramework()` from the core Bootstrap is run, the entry is not there - and thus the exception is trigegred that the news cache identifier ist not there. I'm not sure in which order they are loaded, but it seems here is something wrong how the core loads configuration.

But this only happens when using proxy classes.

**Comment by foobar13372** [comment] 2019-07-31 05:58
Ah, I think this happens because the news ClassLoader is registered as an autoloader. Which is run whenerver a class is called - this seems to happen while the bootstrap runs. and the news ClassLoader tries to get the cache configuration, which isn't loaded then.

**Comment by foobar13372** [comment] 2019-07-31 06:07
In `EXT:news/Classes/Utility/ClassLoader.php` in method `initializeCache()` The GLOBALS cache array contains "news". The at the same line the CacheManager (which is Singleton and already instantiated) does not know it.

**Comment by foobar13372** [comment] 2019-07-31 06:12
Got it! In out case it's the extension `static_info_tables` (comes implicitly with `l10nmgr`) which accesses the CacheManager before the configuration is fully loaded. Thus leaving behind an incomplete loaded singleton CacheManager.

Not sure

**Comment by georgringer** [comment] 2019-08-13 04:49
@foobar13372 which solution do you propose?

**Comment by foobar13372** [comment] 2019-08-19 09:23
If I knew a solution I already had post it. ;)

I think we have fundamental architectural race-condition here which can only be solved by a complete drop of this feature all toegther and replace it by something else.

**Comment by dr2okevin** [comment] 2019-09-20 10:39
I have the same Issue. TYPO3 9.5.9, News 7.3.1. 
Would it be possible to register a new cache in the ClassLoader if it is missing?

**Comment by stigfaerch** [comment] 2020-01-17 11:22
I had the same problem when configuring a slot/signal connection. I found a solution though.
First I configured the connection with the static variable 'class'
```
    $signalSlotDispatcher->connect(
        \GeorgRinger\News\Controller\NewsController::class,
        \GeorgRinger\News\Controller\NewsController::SIGNAL_NEWS_LIST_ACTION,
```

By changing the class name to a string with the name of the class instead, the problem disappeared
```
    $signalSlotDispatcher->connect(
        'GeorgRinger\\News\\Controller\\NewsController',
        'listAction',
        ...
```

**Comment by DavidBruchmann** [comment] 2020-06-15 21:30
I've a resembling message, just the string is completely empty, but news is showing up in the backtrace:
```
Tue, 16 Jun 2020 03:52:04 +0700 [CRITICAL] request="86bbe5e9f6085" component="TYPO3.CMS.Core.Error.DebugExceptionHandler":
 Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1203584729: "" is not a valid cache identifier. | 
 InvalidArgumentException thrown in file \typo3\sysext\core\Classes\Cache\Frontend\AbstractFrontend.php in line 50. 
 Requested URL: http://localhost/typo3/index.php?route=%2Frecord%2Fedit&token=--AnonymizedToken--&edit%5Btx_news_domain_model_news%5D%5B2%5D=edit&returnUrl=%2Ftypo3%2Findex.php%3Froute%3D%252Fmodule%252Fweb%252Flist%26token%3De1ed94f1fd1d83996b592fa54595359245076768%26id%3D44
 - {"TYPO3_MODE":"BE","exception":"InvalidArgumentException: \"\" is not a valid cache identifier. 
 in \\typo3\\sysext\\core\\Classes\\Cache\\Frontend\\AbstractFrontend.php:50\nStack trace:
  #0 \\typo3\\sysext\\core\\Classes\\Cache\\CacheManager.php(345): TYPO3\\CMS\\Core\\Cache\\Frontend\\AbstractFrontend->__construct('', Object(TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend))
  #1 \\typo3\\sysext\\core\\Classes\\Cache\\CacheManager.php(284): TYPO3\\CMS\\Core\\Cache\\CacheManager->createCache('')
  #2 \\typo3\\sysext\\core\\Classes\\Cache\\CacheManager.php(215): TYPO3\\CMS\\Core\\Cache\\CacheManager->createAllCaches()
  #3 \\typo3conf\\ext\\news\\Classes\\Hooks\\DataHandler.php(42): TYPO3\\CMS\\Core\\Cache\\CacheManager->flushCachesInGroupByTag('pages', 'tx_news_uid_2')
  #4 [internal function]: GeorgRinger\\News\\Hooks\\DataHandler->clearCachePostProc(Array, Object(TYPO3\\CMS\\Core\\DataHandling\\DataHandler))
  #5 \\typo3\\sysext\\core\\Classes\\Utility\\GeneralUtility.php(3325): call_user_func_array(Array, Array)
  #6 \\typo3\\sysext\\core\\Classes\\DataHandling\\DataHandler.php(8219): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::callUserFunction('GeorgRinger\\\\New...', Array, Object(TYPO3\\CMS\\Core\\DataHandling\\DataHandler))
  #7 \\typo3\\sysext\\core\\Classes\\DataHandling\\DataHandler.php(8063): TYPO3\\CMS\\Core\\DataHandling\\DataHandler->prepareCacheFlush('tx_news_domain_...', 2, 44)
  #8 \\typo3\\sysext\\core\\Classes\\DataHandling\\DataHandler.php(1241): TYPO3\\CMS\\Core\\DataHandling\\DataHandler->processClearCacheQueue()
  #9 \\typo3\\sysext\\backend\\Classes\\Controller\\EditDocumentController.php(562): TYPO3\\CMS\\Core\\DataHandling\\DataHandler->process_datamap()
  #10 \\typo3\\sysext\\backend\\Classes\\Controller\\EditDocumentController.php(426): TYPO3\\CMS\\Backend\\Controller\\EditDocumentController->processData(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #11 [internal function]: TYPO3\\CMS\\Backend\\Controller\\EditDocumentController->mainAction(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #12 \\typo3\\sysext\\backend\\Classes\\Http\\RouteDispatcher.php(66): call_user_func_array(Array, Array)
  #13 \\typo3\\sysext\\backend\\Classes\\Http\\RequestHandler.php(94): TYPO3\\CMS\\Backend\\Http\\RouteDispatcher->dispatch(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #14 \\typo3\\sysext\\extbase\\Classes\\Middleware\\SignalSlotDeprecator.php(49): TYPO3\\CMS\\Backend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #15 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Extbase\\Middleware\\SignalSlotDeprecator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Backend\\Http\\RequestHandler))
  #16 \\typo3\\sysext\\backend\\Classes\\Middleware\\SiteResolver.php(69): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #17 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #18 \\typo3\\sysext\\backend\\Classes\\Middleware\\AdditionalResponseHeaders.php(41): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #19 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\AdditionalResponseHeaders->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #20 \\typo3\\sysext\\backend\\Classes\\Middleware\\OutputCompression.php(47): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #21 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #22 \\typo3\\sysext\\backend\\Classes\\Middleware\\BackendUserAuthenticator.php(77): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #23 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #24 \\typo3\\sysext\\backend\\Classes\\Middleware\\BackendRouteInitialization.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #25 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\BackendRouteInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #26 \\typo3\\sysext\\backend\\Classes\\Middleware\\ForcedHttpsBackendRedirector.php(55): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #27 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\ForcedHttpsBackendRedirector->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #28 \\typo3\\sysext\\backend\\Classes\\Middleware\\LockedBackendGuard.php(73): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #29 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\LockedBackendGuard->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #30 \\typo3\\sysext\\core\\Classes\\Middleware\\NormalizedParamsAttribute.php(45): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #31 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #32 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(78): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #33 \\typo3\\sysext\\core\\Classes\\Http\\AbstractApplication.php(85): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #34 \\typo3\\sysext\\backend\\Classes\\Http\\Application.php(63): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #35 \\typo3\\sysext\\core\\Classes\\Http\\AbstractApplication.php(97): TYPO3\\CMS\\Backend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #36 \\typo3\\index.php(25): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()
  #37 \\typo3\\index.php(26): {closure}()
  #38 {main}"}
```
My extension is https://github.com/DavidBruchmann/wdb_news_snapin and comes with some data too, it's enough to create somewhere a newsrecord and in tab extra play a bit around with the options and trying to save then. Also install-tool and extension-manager break.
This behavior is in TYPO3 Versions 9 and 10.

**Comment by georgringer** [comment] 2022-06-22 05:16
closing issue as can not be reproduced in latest versions

**Closed by georgringer** 2022-06-22 05:16 UTC
Labels: Needs feedback from author
