### ISSUE TITLE
Lack of items in News Administration and newsPidListingAction error

### ISSUE THREAD

**Issue by plojewski** [georgringer/news#1851] opened 2022-09-21 10:39 UTC
Hi there,
in version 10.0.0 (Typo 10.4.32) News Administration module don't show any items. When I click to "See all pages containing news records" an error occured:

<pre>
An action "newsPidListingAction" does not exist in controller "GeorgRinger\News\Controller\AdministrationController".
</pre>

**Comment by MatthiasPeltzer** [comment] 2022-09-21 12:08
Hi... I have a 503 also. @georgringer is it because it is no longer a part of the news extension? Than it should not be there anyway or should have a note or page behind it that this is only available as a paid extension? @plojewski I think this is the cause?

**Comment by plojewski** [comment] 2022-09-21 12:52
@MatthiasPeltzer I think News Administration module should be as a part of news ext.

**Comment by georgringer** [comment] 2022-09-21 17:23
@plojewski how can this be reproduced? where do you click to see this error? 

I certainly understand your opinion that every feature should be available for everyone, ideally without bugs and without costs but this is not possible and I doubt you provide your services completely for free

**Comment by plojewski** [comment] 2022-09-22 08:09
@georgringer That's not what I meant and I understand your point :) It's just that this module has been around forever, so we assume you didn't intend to remove it in plugin version 10. I clicked on News Administration, then on the records folder (none displayed), then on "See all pages containing news records".

**Comment by georgringer** [comment] 2022-09-22 09:45
it is intended. Either agencies and their clients start supporting developers properly or there are paid plugins which cover the  expenses. I would be more than happy to discuss such things on slack, phone or in person.

**Comment by transdata** [comment] 2022-10-10 14:50
I can understand this point of view very well, but, on one hand, I would like it if this was communicated before an update where I am then confronted with the facts, on the other hand, TYPO3 lives from the work of an open source community, because otherwise it will be gone very quickly because Wordpress will eat its way into the users even further.
To be honest, I'm also convinced that someone with your skills would not have to worry about orders and lack of clients.
I apologize if I'm wrong, but we've witnessed the development of subscription models etc. in recent years.
If you are already working with costs, then not through the back door but rather more transparently and communicatively.
I think your work is great and I would like to take this opportunity to thank you again, but you have to search the changelogs yourself to find information about it.
Personally, I don't think it's the most successful move. Essentially, one could also say that this extension should have long since been integrated into the core of TYPO3 and should be financed from TYPO3 development.
It also works with Wordpress, and at €150 per installation it's already an enterprise price, whether that will help to spread TYPO3, I'm skeptical.
Because other extensions are not developed further forever or are just "pre-developed" and require further programming.
But just my humble 5 cents as an objection.

**Comment by georgringer** [comment] 2022-10-10 15:05
I love open source and invest tons of hours for free. On the other side there are agencies which of course sell therir work time to clients and this is fine but there is a lack of giving back from many agencies, developers and integrators.
Yes of course I make money from client work but they pay me for work I do for them and I don't double the invoiced hours just to get money for my open source work.

Of course everything can be communicated better, earlier and maybe nicer. I added it to the changelog which is the central place and also at the additional addon section.

I am really interested to understand others better, maybe we can have a talk via slack, mail or phone? Feel free to reach out to me!

**Comment by transdata** [comment] 2022-10-11 08:26
I don't want to be a nuisance here, but I think that such discussions belong in the public domain and exactly where the feedback is generated. If I'm overdoing it, I apologize in advance. But it is important for me to get rid of the points of my consideration.
Ultimately, everyone who installed your extension is now forced to pay in order to offer their customers the options that were available before the update.
In essence, I think there is a lot that comes together, whether it bears the development costs, of course, they are certainly not insignificant, but precisely because of this awareness of the extension and the name of the developer associated with it, you will have outperformed other providers in the competitive process.
This is also a monetary advantage that should be factored in.
Also all the work of those here who give feedback and find and communicate bugs etc. in their work. They also work on a voluntary basis and are not remunerated now that the plugin is chargeable.
The same applies to those who help develop and further develop the core system, i.e. the basis for the operability of your extension, and the money does not matter there either. Or only with a voluntary donation or as a supporter, where when I worked for agencies that then had this seal, I only saw an extension if it could be deducted as a return on costs.
The list of effects is long and if everyone soon wants money for their open source work, then TYPO3 is history, because then the agencies go to systems that cost money right from the start and from which claims can also be derived.
This core extension in particular is now leading the way with an example of how this process can be triggered or even accelerated.
I think it's perfectly fine to ask for money for your work, of course, but with 150€ you won't set up a small system to try something out or program it because it doesn't pay off, every development system then goes into the production system and maybe even more a backup of which are therefore not insignificant in the costs.
10 years ago, TYPO3 was at a very shaky point and was more and more marginalized, then some long overdue steps were taken, I think you should be careful, because especially in tense times it can backfire in the end.
There are a few companies that have now specialized in TYPO3 extensions, the prices of which are increasing year by year, i.e. by 100% or more, there are reasons for that, and in the end you are developers who are highly specialized in the competition about the last enterprise customers, who have a vanishing share of the entire community.
But then the developer prices drop very quickly, and some agencies I know have completely switched to Wordpress.
Of course, I can also be completely wrong and no matter what you do, it has no influence, but I just perceive it differently. Please don't misunderstand me, it's my opinion and I would like to thank you again for your work and the extension that has accompanied me since it was created. I could have switched to slack, but I wanted to share my humble thoughts with others who are wondering what's going on. Thank you for your support!!!

**Comment by georgringer** [comment] 2022-10-11 08:47
yes such things should be discussed in public, however sometimes it is easier to just use the phone and call someone. 
I really would love to give everything away for free and do more open source work but free licensing just doesn't mean that it is free for me and if just everyone who uses my extensions pay 5€ per installation per year it would be amazing but as this doesn't happen (and I don't know whay) I didn't yet have any better idea yet.
I don't know your situation if you are part of an agency, freelancer but I would be more than happy to implement something which makes more people happy and ensures at the same time that there is EXT:news available for v12

**Comment by georgringer** [comment] 2022-10-11 09:22
FYI I added something at https://typo3.slack.com/archives/C03TG7QJT/p1665480095320279

**Comment by BastianBalthasarBux** [comment] 2022-10-11 11:20
To say it loud and clearly:
Websites which are using tx_news that much, that the use of the administration module is mandatory, or just pretty important, are most likely corporations or organisations, which are making money with their content, or at least their content is a vital part of their business model.
I think, 150 bucks are not too much then.
All others can use tx_news without any restriction but just have no Administration module (which is 99% of my usage, where I deactivated the administration module since ages anyways, as they don't need it for one news entry per month ...)

**Comment by DavidBruchmann** [comment] 2022-10-11 20:39
@georgringer I think a dual license might be justifiable:  

- for commercial projects 50 € / year
- for non-commercial projects free

I've chosen the fee relatively low, but if you'd get it from every commercial project, the sum would be sufficient I guess. Nevertheless, I never stick to this value.

The problem with voluntary fees is that it's hard to invoice it to the customer so easily, so a commercial license makes it clear that avoiding the fees is lawless.  
It might be hard to determine it for some associations or other corporations if it's commercial or not and so there might exist some loopholes with this simple model. For some the fee (or the shift to it) might pose a burden, so a smart communication of that change is advisable.

I think the general idea is justified and that the TYPO3 Association could support it by creating an own and explicit version of a dual license. The price shouldn't be part of it but determined by every extension author that is providing an extension with this license.  
One aspect should be also that some customers have many domains where each of them has a relatively low ROI, so for those the costs should be reducible but not be calculated for each domain. But domain and project are not the same anyway, and it might be difficult to define those things in detail. Simple example: for a TYPO3 website a language specific domain is possible, and charging for each language might not be fair or justifiable, especially in comparison to those who solve it within one domain only.

**Comment by georgringer** [comment] 2022-10-11 21:00
dual licensing is not possible as long as the code you are using is dependent on a license like GPL. dual licensing TYPO3 would be possible if every contributor would be asked and agrees.

> The problem with voluntary fees is that it's hard to invoice it to the customer so easily, so a commercial license makes it clear that avoiding the fees is lawless.

I really don't see this is a customer issue but a freelancer/agency issue. If you bring your car to the repair shop, it doesn't matter which percentage of the payment goes into rent, into tools or into whatever. In a perfect world, the agency would just bill one additional hour or use whatever percentage and use that money to try to ensure that the tool they use and make money of is developed further.

even with just 20€ per client per year it would be enough for kind of everything. there wouldn't be a need for a paywall, no need for thinking about dual licensing and nothing else.

**Comment by DavidBruchmann** [comment] 2022-10-11 21:18
Currently GPL is required to publish an extension in TER. The TYPO3 Association could consider this restriction perhaps, here I bring up again the "TYPO3 Association dual license".  

Nevertheless I note your other aspects and agree in general.

**Comment by georgringer** [comment] 2022-10-11 21:20
even if you don't publish the extension it is GPL because it uses GPL code and can't work with something else. if it would be general PHP code which can be used by other CMS (With other licenses), then I could think about a different license.

**Comment by wkrawczak** [comment] 2022-10-28 09:01
I think what the original poster meant (although I may be mistaken) and I agree with him - the "News Administration" module should either not appear in the backend if not installed OR when clicking on it an information about licensing should appear instead with a link (if possible), so it is clear. I personally was also surprised there's an error and found the information in the changelog later on.
I'm not against this licensing model, think it's still fair, but the lack of information is a problem. Unless this happens only because we've upgraded (using composer) from 9.4 to 10? But I think it shouldn't matter in that case.

**Comment by georgringer** [comment] 2024-05-17 06:17
closing issue for now

**Closed by georgringer** 2024-05-17 06:17 UTC
Labels: Bug, Needs feedback from author
