### ISSUE TITLE
Problem when inserting yag plugin into news item

### ISSUE THREAD

**Issue by larpwelt** [georgringer/news#114] opened 2016-09-27 15:01 UTC
Hi!

This is a shamless crossposting. Because I don't know, if I should blame News or YAG, I post this in both Issue Trackers.

I'm using small galeries inside of news elements. That worked fine until I did some updates.

When I add the plugin as content element into the news element, I get no error. But when I click the content element and try to expand it, the progress bar stops short for the end and never ends.

A second click on the content element opens the content element. But the source tab from yag keeps without any function. It look's like there are some JS and CSS missing.

I'm using:
•Typo3 7.6.6
•YAG 4.1.2
•News system (news) 5.2.0
•pt_extlist 2.3.0
•pt_extbase 2.2.0

![4ac9be82-486b-11e6-9c28-89f45beefef6](https://cloud.githubusercontent.com/assets/6368428/18879208/b6657a7e-84d3-11e6-8473-d7e9a934e1e1.png)
![09522858-486c-11e6-9dab-0b85699abb36](https://cloud.githubusercontent.com/assets/6368428/18879207/b6623238-84d3-11e6-9c6e-33f2acde48ca.png)

**Comment by georgringer** [comment] 2016-09-28 03:52
it would be nice if you could put links to the other issue tracker as well.

please update to latest core version and retry!

**Comment by georgringer** [comment] 2016-10-03 12:24
I close this issue because of lack of feedback

**Comment by larpwelt** [comment] 2016-10-10 15:25
Hi!

Sorry about being a bit late to answer!

The link to my cross posting inside the yag tracker is: https://github.com/YAG-Gallery/yag/issues/79

It may take a while to reproduce the problem with with a newer version of Typo3. Because I would like to stay with the version in my live system. So I have to setup a development version of my side first.

**Comment by larp-welt** [comment] 2016-10-10 18:00
I seems, it's ok to write in german in this bug tracker...

Ich habe meinen ganzen Mut zusammen genommen, und ein Update auf die aktuelle LTS-Version von Typo3 gemacht. Ich bin jetzt auf der Version 7.6.11.

Das Problem besteht noch immer!

**Comment by georgringer** [comment] 2016-10-11 06:13
please still use english

**Comment by larpwelt** [comment] 2016-10-13 14:07
Just for the english speaking readers: I've updated my Typo3 to version 7.6.11 ... the problem is still alive!

Sorry about my posting in german, that won't happen again!

**Comment by SuddenlyRust** [comment] 2016-11-23 16:35
Hello guys.

Just wanted to inform that this problem still exist in the current version. I am using following settings:
![short](https://cloud.githubusercontent.com/assets/14092921/20568247/33193f34-b19c-11e6-9be5-05fb19f865f3.PNG)
TYPO3 Core version: **7.6.13**
Extensions:
[yag](https://typo3.org/extensions/repository/view/yag) **4.1.2**
[news ](https://typo3.org/extensions/repository/view/news/) **5.2.0**

Problem explanation:
First of all. Both extensions work completly fine stand alone. The problem is following when I want to use a yag-album (or what ever) as a Content Element inside a News-Record. It won't work on the normal way.

Steps to recreate this bug:
Step 1: Select a News-record in the backend
![step-1](https://cloud.githubusercontent.com/assets/14092921/20568843/1bb1d520-b19e-11e6-8786-2c2357805c3e.jpg)

Step 2: Choose the second tab "Content Elements"
Step 3: Click on "Create new"
![step-2](https://cloud.githubusercontent.com/assets/14092921/20568991/c6b77718-b19e-11e6-8b34-4c16e087fecf.jpg)

Step 4: Select "Insert Plugin" as Type in the Content Element. A refresh is required and it should look like in the picture below.
![step-4](https://cloud.githubusercontent.com/assets/14092921/20569085/16cab594-b19f-11e6-9f23-91c3780415ec.jpg)

Step 5: In the second tab "Plugin" you choose now "YAG - Yet Another Gallery". A refresh is required and now the problem starts. I get following error message:
![step-5](https://cloud.githubusercontent.com/assets/14092921/20569252/c1f1870e-b19f-11e6-9865-ba3eded8e0a6.jpg)
![step-6](https://cloud.githubusercontent.com/assets/14092921/20569312/ec93ff0a-b19f-11e6-9d59-61f621b681eb.jpg)

Somehow JQuery is not loaded in the backend here. Or at least that is what I think. But it is impossible because it's called from "jquery-2.1.4.js:8605". I have really no idea how this is possible. 
This happens every time and because of this reason it is now not possible to select a Gallery or Album from the yag extension
![step-7](https://cloud.githubusercontent.com/assets/14092921/20569459/6b6e09c4-b1a0-11e6-8b65-beaee02a9e69.jpg)

But @larpwelt (or @larp-welt maybe the same person) found a work around to add the yag content element into it and it works completely fine. I am very inexperienced and have no idea how to fix this problem. Maybe someone here can look at it. Both extensions are awesome and it would be really great if we could use them easy together.

Here is a instruction to add it another way (not very comfortable):
1. Do all steps like previous and save it. (Short: Create a content element inside the news record and choose its type as yag-plugin)
2. Go into the List view.
3. Select "Display information" on the right side of the news record. It's a button with a "i" on it. Now a popup window appears with various information about this record
4. Scroll down. There are all references of the item
5. Click on edit of the content element (what we created on step 1)
6. Click on the second tab "Plugin" and choose as Plugin Options the tab "Source"
7. Volla. Now its possible to choose a gallery.

![step-8](https://cloud.githubusercontent.com/assets/14092921/20569883/e57c7380-b1a1-11e6-9db6-b3b3fd9cf2f2.jpg)
Now with this method it is possible to add yag into a news record. And it works fine and is displayed in the front end.

I hope this instruction can help someone. (I will copy paste this in the YAG issue forum)
Thank you very much for your time.

Best regard,
@SuddenlyRust

**Comment by larp-welt** [comment] 2017-06-06 09:33
Hi!

I did an update on my site to Typo3 7.6.18 - problem is still there! :-(

I'm using YAG 4.2.1 and News 6.0.0.

**Comment by georgringer** [comment] 2018-03-28 14:50
Even though the issue is valid, yag seems to be not supported anymore for 8+ and next news version is for 8+9. therefore I am closing this issue.

**Closed by georgringer** 2018-03-28 14:50 UTC
Labels: Bug, Needs feedback from author
