### ISSUE TITLE
hidePagination

### ISSUE THREAD

**Issue by gtedv** [georgringer/news#1664] opened 2021-11-30 10:02 UTC
## Bug Report

**Current Behavior**
plugin.tx_news.settings.hidePagination = 1 doesn´t work anymore

**Expected behavior/output**
If this option is set in TS pagination should disappear.

**Environment**
- TYPO3 version(s): 10.4.21
- news version: 9.0.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 10

**Possible Solution**

**Additional context**
Maximum number of records to display is set to one in plugin configuration

**Comment by georgringer** [comment] 2022-03-15 22:49
don't really understand what does not work by looking at the template

```html
<f:if condition="{settings.hidePagination}">
					<f:then>
						<f:for each="{news}" as="newsItem" iteration="iterator">
							<f:render partial="List/Item" arguments="{newsItem: newsItem,settings:settings,iterator:iterator}" />
						</f:for>
					</f:then>
					<f:else>
                        <f:if condition="{settings.list.paginate.insertAbove}">
                            <f:render partial="List/Pagination" arguments="{pagination: pagination.pagination, paginator: pagination.paginator}" />
                        </f:if>
                        <f:for each="{pagination.paginator.paginatedItems}" as="newsItem" iteration="iterator">
                            <f:render partial="List/Item" arguments="{newsItem: newsItem,settings:settings,iterator:iterator}" />
                        </f:for>
                        <f:if condition="{settings.list.paginate.insertBelow}">
                            <f:render partial="List/Pagination" arguments="{pagination: pagination.pagination, paginator: pagination.paginator}" />
                        </f:if>
					</f:else>
				</f:if>
```

have you found a solution?

**Comment by gtedv** [comment] 2022-03-16 15:15
Hello Georg, my solution until now is to use tx_news 8.6.0, that works fine.  
I think the setting for enable / disable pagination in TS and in the backend will not be evaluated anymore, but I don´t know why.
Best regards

**Comment by georgringer** [comment] 2022-06-09 19:11
I can't reproduce it and therefore closing the issue

**Closed by georgringer** 2022-06-09 19:11 UTC
Labels: Bug, Needs feedback from author
