### ISSUE TITLE
Next/Previous link does not work in second language

### ISSUE THREAD

**Issue by nfrische** [georgringer/news#859] opened 2019-02-22 09:41 UTC
I have a problem with the next/previous links on the overvie page in the second language (English). My standard language is German and everything works well here. When I click on the next link in the English language (to show more news), I end up on the second German page and not on the second English page.

Typo3 Version: 9.5.4
news: 7.0.8
Is my TYPO3 installation set up with Composer (Composer Mode): np

I also tested this at another website in Typo3 version 9.5.3 und news version 7.0.8 and here also works everything well.

**Comment by whiteroom** [comment] 2019-03-13 12:34
And I would like to add the following:

Template News/Detail.html
has hardcoded sortField="datetime" which is not only unnecessary, but leads to cryptic next/previous navigation in case the author prefers manual sorting or sorting by title etc.

Georg, why not:
`<n:simplePrevNext pidList="{newsItem.pid}" news="{newsItem}" as="paginated" sortField="{settings.orderBy}">`

**Comment by georgringer** [comment] 2022-06-24 06:53
duplicate of https://github.com/georgringer/news/issues/731

**Closed by georgringer** 2022-06-24 06:53 UTC
