### ISSUE TITLE
Unable to upload or add media files or related links to news record.

### ISSUE THREAD

**Issue by errolmars** [georgringer/news#1468] opened 2021-02-26 09:00 UTC
## Bug Report

**Current Behavior**
The media upload is not adding the file to news record from newly uploaded or file that's already in fileadmin.
**Expected behavior/output**
Usually after adding a media file to a news record you are presented with the preview of the image and its attributes. However this isn't happening for me.

**Environment**
- TYPO3 version(s): [10.4.13]
- news version: [8.5.2]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [Debian 4.9.189-3]
- PHP Version [7.2.34]

**Possible Solution**
I solved my immediate problem by rolling back to News System 8.5.1.

**Additional context**
This issue also affects adding related links to the article.

**Comment by georgringer** [comment] 2021-11-05 11:21
can't reproduce this, the backend is fully default core, nothing special from ext:news happening here . closing the issue

**Closed by georgringer** 2021-11-05 11:21 UTC
