### ISSUE TITLE
[bug] NewsImportService > l10n_parent news gets overriden by localized ones upon import

### ISSUE THREAD

**Issue by vizlot** [georgringer/news#796] opened 2018-11-13 00:58 UTC
## Bug Report

**Current Behavior**
When trying to import tt_news, those news which has language version (with l18n_parent) would fully override their parents.

***DB in tt_news***
uid	-- title -- parent_uid		
838	-- Language overlay title -- 837
837 -- Original title	-- 0

***DB in tx_news after import ***
uid --  title ----------------------- import_id -- parent -- lang
176 -- Language overlay title	 ---- 838	 -------- 140 --- 1
140 -- Language overlay title	 ---- 838	 -------- 140 --- 1

**Expected behavior/output**
*** EXPECTED DB in tx_news after import ***
uid --  title ----------------------- import_id ---- parent ---- lang
176 --  Language overlay title ---- 838 ----------140 -- 1
140 --  Original title -------------- 837 ----------0 ---- 0

**Possible Solution**
Disabling $this->newsRepository->update($news); solves the problem (line 119 NewsImportService.php)

**Environment**
- TYPO3 version(s): 8.7.20
- news version: 7.0.7
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by franzkugelmann** [comment] 2019-03-05 07:30
I can confirm the behaviour and possible "solution" with TYPO3 8.7.24, news 7.0.7, non composer mode.
Thanks @vizlot 
However, the issue seems to be in the EXT:news_ttnewsimport/Classes/Jobs/TTNewsNewsImportJob.php
`protected $numberOfRecordsPerRun = 30;`
If you remove that line or set the limit so high that all news will be imported in one run, then the problem is  also gone.

**Comment by joximu** [comment] 2019-08-08 14:41
Hi
I'm not sure if I had the same.

I have old News categories in 3 languages (default EN with DE and ES as additional langs).
Some of the categories were children of a main category.

The import was fine for the main categories - there were all items incl. translations in the sys_cat table. but the subcategories were not translated.

After digging in the code I found in news/Classes/Domain/Service/CategoryImportService.php that an imported category gets some post processing if it has a translation *OR* if it has parents. And this was an excluding OR.... because the "action" added for the post processing could be either 1 or 2....
I write my simple solution here - it's for news Version 3.2.8 but the code still looks almost the same therefore should be easily adopted to newer releases:

It's in "public function import(array $importArray) {" 
in the first foreach block add this as a third if block:


```
                        if ( (!empty($importItem['title_lang_ol'])) && ($importItem['parentcategory']) ) {
                                $this->postPersistQueue[$importItem['import_id']] = array(
                                        'category' => $category,
                                        'importItem' => $importItem,
                                        'action' => self::ACTION_CREATE_L10N_CHILDREN_CATEGORY + self::ACTION_SET_PARENT_CATEGORY,
                                        'titleLanguageOverlay' => $importItem['title_lang_ol'],
                                        'parentCategoryOriginUid' => $importItem['parentcategory']
                                );
                        }

```

and in the second foreach block add this as a third switch item:

```
                                case self::ACTION_CREATE_L10N_CHILDREN_CATEGORY + self::ACTION_SET_PARENT_CATEGORY:
                                        $this->createL10nChildrenCategory($queueItem);
                                        $this->setParentCategory($queueItem);
                                        break;
```

This worked for me - I got all sys_cat now including children, translations and translated children...

**Comment by georgringer** [comment] 2024-05-17 06:08
code changed a couple of times, closing issue therefore. feel free to reopen a new one if still relevant

**Closed by georgringer** 2024-05-17 06:08 UTC
