### ISSUE TITLE
The requested resource "/module/web/NewsAdministration" was not found.

### ISSUE THREAD

**Issue by lukasdoerr** [georgringer/news#1500] opened 2021-03-25 10:26 UTC
## Bug Report

**Current Behavior**
I have updated the news extension in a TYPO3 10.4.14 System to 8.5.2 and i cant access the backend module "News Administration". It shows "The requested resource "/module/web/NewsAdministration" was not found." which could be in connection to the security update last week. However, i can still manage the news via the List Module

**Expected behavior/output**
Normally it would show the backend module news. with a news list.

**Environment**
- TYPO3 version(s): 10.4.14
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): NO
- OS: Windows 10 / Firefox 87.0

**Possible Solution**
There were allready some fixes in other versions. Maybe they have something in common with the new security update.

**Additional context**
I updated the news extension from 8.3.0 because Media Uploads were not working anymore. That was, because this version didnt support the new sorting js - after a update, it worked then but the Backend module stopped.

**Comment by georgringer** [comment] 2021-11-05 09:38
I can't reproduce that and will close the issue

**Closed by georgringer** 2021-11-05 09:38 UTC
