### ISSUE TITLE
Error with NewsAdministration in 9.5.18 with news 8.3.0

### ISSUE THREAD

**Issue by gtedv** [georgringer/news#1289] opened 2020-06-01 08:09 UTC
An error appears in an updated TYPO3 installation (from 8.7 to 9.5) when I click the search box in the news administration. What search critera I choose dosn´t matter.

TYPO3\CMS\Backend\Routing\Exception\ResourceNotFoundException
The requested resource "/module/web/NewsAdministration" was not found.

- TYPO3 version(s): 9.5.18
- news version: 8.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 10

It works fin in TYPO3 8.7.32 with news 7.3.1

**Comment by typo3ua** [comment] 2020-06-02 20:13
The same after update from 9.5.16 to 9.5.18
```
(1/1) #1425389240 TYPO3\CMS\Backend\Routing\Exception\ResourceNotFoundException
The requested resource "/module/web/NewsAdministration" was not found.
```

**Comment by JarvisH** [comment] 2020-06-05 21:30
Duplicate of #1271. This has been resolved in the master branch https://github.com/georgringer/news/pull/1273

**Comment by medarob** [comment] 2020-06-15 07:56
I have the same error in TYPO3 9.5.19. I wanted to filter news by a certain category so I checked one category and clicked on the "search"-button and then the error appeared.

**Comment by kveldscholten** [comment] 2020-07-07 08:13
Following works by me with this pull request changes https://github.com/georgringer/news/pull/1273/files

After that you must add slash at the end in this file https://github.com/jonakieling/news/blob/f2e9b04239bcb8bfa633026743b9caca3bfef85e/Classes/Backend/RecordList/RecordListConstraint.php#L34
 from
`return strpos('/module/web/NewsAdministration', $vars) !== false;`
to
`return strpos('/module/web/NewsAdministration/', $vars) !== false;`


i use TYPO3 v9.5.19 and News v8.3.0

**Comment by JarvisH** [comment] 2020-07-07 08:28
This error is caused by the strpos parameters being in the wrong order I think

**Comment by georgringer** [comment] 2020-07-30 17:58
fixed now in master

**Closed by georgringer** 2020-07-30 17:58 UTC
