### ISSUE TITLE
fetch() call throw exception under PHP 8.1 if DB driver is set to pdo_mysql

### ISSUE THREAD

**Issue by mediaessenz** [georgringer/news#1789] opened 2022-06-01 11:15 UTC
## Bug Report

**Current Behavior**
All ->fetch() calls throwing an exception under PHP 8.1, if the DB driver is set to pdo_mysql.

**Expected behavior/output**
No error

**Environment**
- TYPO3 version: 11.5.10
- DB driver: pdo_mysql
- news version: 9.4.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: OSX 12.4

**Possible Solution**
Use fetchAssociative() instead

**Comment by mediaessenz** [comment] 2022-06-01 13:22
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception

PHP Runtime Deprecation Notice: PDOStatement::fetch(): Passing null to parameter #1 ($mode) of type int is deprecated in /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php line 138

**Comment by georgringer** [comment] 2022-06-01 18:03
Looks like a different error then initially reported... Please add a stack trace and how to reproduce.
Furthermore it is just a warning but of course should be fixed

**Comment by mediaessenz** [comment] 2022-06-02 09:29
Here is the exception stack trace:
<img width="500" alt="Exception-Stack-Trace" src="https://user-images.githubusercontent.com/16038153/171598900-ac6b1ee0-690f-4c3c-93d1-ff72477f22d5.png">

To reproduce, use a TYPO3 11.5.10 system and set the driver of the Default DB to "pdo_mysql". 
The underlying system should be PHP 8.1 and MariaDB 10.5 (I think the db version is not important here).

If you open a detail page of a news, the exception should appear.

**Comment by georgringer** [comment] 2022-06-02 18:05
thanks, confirmed. nevertheless this won't be fixed until support for version 10 is stopped.

**Closed by georgringer** 2022-06-02 18:05 UTC
Labels: Needs feedback from author
