### ISSUE TITLE
Error when selection "Detail view"

### ISSUE THREAD

**Issue by Ceremony64** [georgringer/news#854] opened 2019-02-18 09:30 UTC
**Current Behavior**
1. Add the news frontend plugin to a page.
2. Select "Detail view" for the first configuration option "What to display".
3. Save the element and try to edit the plugin content element again.
4. An error occurs: Missing "renderType" in TCA of field "[tt_content][pi_flexform]".

**Expected behavior/output**
Obviously no error and the element should remain editable

**Environment**
- TYPO3 version(s): 8.7.24
- news version: 7.0.8
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Debian 9

**Additional context**
Changing switchableControllerActions directly in tt_content->pi_flexform back to the default value (News-&gt;list;News-&gt;detail) lets you edit the content element again. Swapping the order of the actions around results in the same error message

**Comment by JarvisH** [comment] 2019-02-23 13:15
Hello.

I just tested this issue in Typo3 8.7.24 and with News 7.0.8, only difference being I use composer mode.

I could not reproduce this issue. Could it be a caching-problem of some sort? Did you have the issue in an existing Typo3-System which was updated, or was it a new installation?

In the current news extension flexform file there are no select fields which are missing the "renderType" property which makes it all the more odd.

**Comment by georgringer** [comment] 2019-03-08 08:47
closing this issue as I can't reproduce

**Comment by Ceremony64** [comment] 2019-04-04 13:39
I have finally figured out what is causing this issue! [This PageTS setting](https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Configuration/TsConfig/Index.html#categoryrestrictionforflexforms):
`tx_news.categoryRestrictionForFlexForms = 1`

Set it and detail view (among other news plugin types) break in the backend! Even when you have pages via `TCEFORM.tx_news_domain_model_news.categories.PAGE_TSCONFIG_IDLIST` defined...

**Comment by georgringer** [comment] 2019-04-08 18:50
sorry can't reproduce. this setting also only adds an additional where clause.

**Comment by Ceremony64** [comment] 2019-04-09 08:22
Heres the DB + Typo3 structure as a minimal setup to reproduce the issue: https://files.catbox.moe/gohdrw.xz (.tar.xz file)

Username and password for everything is issue854. Using Typo3 8.7.24 and MariaDB 10.1.37 (InnoDB 5.6.41-84.1).

Basically set within the news plugin "Category restriction" to "Page TsConfig" and the put `tx_news.categoryRestrictionForFlexForms = 1` in the PageTS setting

**Comment by Fischer-Simon** [comment] 2019-05-07 12:43
I found the problem. Will issue a pull request.

**Comment by swisschocolate** [comment] 2019-08-07 10:06
I can reproduce it with Typo3 9.5.8 and news 7.2.3. As @Ceremony64 found out it is the PageTS categoryRestriction causing the problem, and the bugfix from @Fischer-Simon is solving it.

**Closed** 2019-08-14 03:37 UTC
Labels: Needs feedback from author
