### ISSUE TITLE
Error 500 on localizing media file

### ISSUE THREAD

**Issue by peterbenke** [georgringer/news#372] opened 2017-07-07 08:16 UTC
TYPO3: 7.6.18
news: 6.0.0

An editor gets a 500-Error, if he tries to localize a media file.
Although he has all possible user-rights.

Thank you.

![news-error-500](https://user-images.githubusercontent.com/14070672/27949243-426c7d12-62fd-11e7-87d9-3dfd9048a2e2.png)

**Comment by mtness** [comment] 2017-07-07 08:24
This error is caused by a regression introduced in T3 v7.6.17 - it is fixed with update 7.6.19,
see https://forge.typo3.org/issues/80855 for details.

**Closed** 2017-07-11 12:32 UTC
