### ISSUE TITLE
Call to undefined method TYPO3\CMS\Backend\View\BackendLayout\Grid\GridColumnItem::getBackendLayout()

### ISSUE THREAD

**Issue by Marat91** [georgringer/news#1230] opened 2020-04-23 10:41 UTC
Call to undefined method TYPO3\CMS\Backend\View\BackendLayout\Grid\GridColumnItem::getBackendLayout()

typo3 v10 immediately after saving the plugin

**Comment by froschdesign** [comment] 2020-04-23 10:45
Duplicate of #1229

**Comment by georgringer** [comment] 2020-04-25 21:45
Core issue

**Closed by georgringer** 2020-04-25 21:45 UTC
