### ISSUE TITLE
Teaser Link "Read more" does not have localized URL

### ISSUE THREAD

**Issue by chrisprog20** [georgringer/news#1051] opened 2019-09-17 08:40 UTC
**Current Behavior**
I have English news records which all have an l10n_parent in German. The teasers in the list view on the English page show the URLs to the German records.

**Expected behavior/output**
The teasers in the list view on the English page show the URLs to the English news records.

**Environment**
- TYPO3 version: 9.5.9
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 7

**Possible Solution**
In news/Classes/ViewHelpers/LinkViewHelper.php you could add the following in around line 140:
`
$configuration['language'] = $newsItem->getSysLanguageUid(); // this line could be added
$url = $this->cObj->typoLink_URL($configuration);
`
**Additional context**

- I have set plugin.tx_news.settings.link.skipControllerAndAction = 0 as otherwise the link generation via the Exbase routeEnhancer does not work.
- I tried all combinations of fallback types and fallback languages in the site configuration: always the URLs to the records of the default language have been generated on the English page.

**Comment by Moongazer** [comment] 2020-06-11 18:38
I can confirm this bug, and the solution by adding `$configuration['language'] = $newsItem->getSysLanguageUid();` works perfect out of the box (added at line 127).

**System:**
TYPO3 9.5.19
News 8.3.0

**More background about my setup:**
- I'm using 2 languages, German (default) and English
- Most news having translations in both languages
- Some news having no translation, so they exist only in default language (German)

View page in German (.../nachrichten/):
- List-View: lists the news teaser in German (OK)
- List-View: the more-link is linking to German detail-page, giving the German slug as parameter, e.g. "/nachrichten/details/nachricht-in-deutsch" (OK)

View page in English (.../news/):
- List-View: lists the news teaser in German, which is expected behavior because of lang-fallback setting (OK)
- List-View: the more-link is linking to English detail-page, giving the German slug as parameter, e.g. "/en/news/details/nachricht-in-deutsch" (**404 Error**)
- If we apply the fix here from above, the more-link will link to the German detail-page because no English translation exists.

**Comment by georgringer** [comment] 2022-06-13 19:52
can't reproduce currently. as this is very old I am closing this issue. feel free to open a new issue if still valid.

**Closed by georgringer** 2022-06-13 19:52 UTC
