### ISSUE TITLE
 List View (without override detail view) Display throws error when placed in a Detail view

### ISSUE THREAD

**Issue by X-Tender** [georgringer/news#1513] opened 2021-05-19 13:02 UTC
## Bug Report

**Current Behavior**
I have a News Detail page with the Detail View Display and a Plugin placed with a List View (without override detail view) Display.
But when I click a News and land at the Detail page I get the error
```
The action "detail" (controller "GeorgRinger\News\Controller\NewsController") is not allowed by this plugin / module
```
On other pages (without a detail view) it works

**Expected behavior/output**
It should show the List view on the Detail View page

**Environment**
- TYPO3 version(s): 10.4.16
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: OSX / Linux

**Comment by dotdash** [comment] 2021-06-02 11:14
This seems to be caused by the change in TYPO3 v10 that uses fully qualified class names in the `controllerConfiguration` array. Therefore [this](https://github.com/georgringer/news/blob/24ddcb09ab7a566a3bc19bea5cb80d78ad673951/Classes/Controller/NewsController.php#L288) check in `isActionAllowed` fails. For TYPO3 v10, the line should probably read:

```php
        $allowedActions = $frameworkConfiguration['controllerConfiguration'][self::class]['actions'] ?? [];
```

**Comment by X-Tender** [comment] 2021-06-02 11:20
Tested it, but didn't worked. Same error.

**Comment by dotdash** [comment] 2021-06-02 11:40
Oh, sorry, I misread your setup. The situation in which I encountered a similar problem was somewhat different.

So to clarify, you have a single page, with two news plugins, one configured for a detail view and one configured for a list view? That's not going to work if the `action` parameter is set, because both plugins see it, and their valid options are mutually exclusive.

It might work if you set:

```
plugin.tx_news.settings.link.skipControllerAndAction = 1
```

but I'm not sure how that might affect other plugins.

**Comment by X-Tender** [comment] 2021-06-02 11:52
I've selected in the "What to display" dropdown the "List view (without overloading detail view)" and thought that it would ignore all params which is for the detail view and just displays the list.
Maybe I understood this option wrong.

`skipControllerAndAction` was removed btw https://github.com/georgringer/news/commit/ab5c6d1c8d133e8fe17f46a7682abe51171ecc01

**Comment by georgringer** [comment] 2022-06-09 11:22
I am closing this issue as I can't reproduce it on my side

**Closed by georgringer** 2022-06-09 11:22 UTC
