### ISSUE TITLE
routeEnhancers with overwriteDemand/* not working in 12

### ISSUE THREAD

**Issue by trokohl** [georgringer/news#2146] opened 2023-07-12 10:34 UTC
## Bug Report

I am not sure if it is a news or Typo3 bug. But since Typo 12 the mapping of the overwriteDemand parameters in combination with the NewsCategoryMapper or PersistedAliasMapper doesn't seem to work anymore.

**Current Behavior**
A call from 
news/testcat 

returns no results but a call with:

news/?tx_news_pi1[overwriteDemand][categories]=1&cHash=0e70fa1f6a2ce75e2db9713a4ddb5aeb

returns results. 
The array overwriteDemand always arrives in the controller with null in the first case.

**Environment**
- TYPO3 version(s): 12.4.x
- news version: 11.1.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

```

routeEnhancers:
  News:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      - routePath: '/'
        _controller: 'News::list'
      - routePath: '/page-{page}'
        _controller: 'News::list'
        _arguments:
          page: 'currentPage'
      - routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      - routePath: '/{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
      - routePath: '/{tag-name}'
        _controller: 'News::list'
        _arguments:
          tag-name: overwriteDemand/tags
    defaultController: 'News::list'
    defaults:
      page: '0'
    aspects:
      news-title:
        type: NewsTitle
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      category-name:
        type: NewsCategory
      tag-name:
        type: NewsTag
  PageTypeSuffix:
    type: PageType
    map:
      'feed.xml': 9818
      'calendar.ical': 9819
```

**Comment by web2date** [comment] 2023-07-31 13:21
Hi Georg, I can confirm that bug too in TYPO3v11 / news v 11.1.2 when overwriting stickylist via DateMenu. Kind regards Andrea

**Comment by georgringer** [comment] 2023-08-05 12:41
tested this with simple
```yaml
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: ''
    map:
      feed.xml: 9818
      calendar.ical: 9819
  News:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      - routePath: '/'
        _controller: 'News::list'
      - routePath: '/category/{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
      - routePath: '/tag/{tag-name}'
        _controller: 'News::list'
        _arguments:
          tag-name: overwriteDemand/tags
    defaultController: 'News::list'
    defaults:
      page: '0'
    aspects:
      category-name:
        type: PersistedAliasMapper
        tableName: sys_category
        routeFieldName: slug
```

and looks good - imho the issue must be in core or ordering of routing :/

**Comment by web2date** [comment] 2023-08-07 10:19
Hi, I have this in my config.yaml
`routeEnhancers:
  News:
    type: Extbase
    limitToPages: [14,18,19]
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: /
        _controller: 'News::list'
      -
        routePath: '/{page-label}-{page}'
        _controller: 'News::list'
        _arguments:
          page: currentPage
      -
        routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      # Date year:
      - routePath: '/{date-year}'
        _controller: 'News::list'
        _arguments:
          date-month: 'overwriteDemand/month'
          date-year: 'overwriteDemand/year'
          page: 'currentPage'
      # Date year + pagination:
      - routePath: '/{date-year}/{page-label}-{page}'
        _controller: 'News::list'
        _arguments:
          date-year: 'overwriteDemand/year'
          page: 'currentPage'
      # Date year/month:
      - routePath: '/{date-year}/{date-month}'
        _controller: 'News::list'
        _arguments:
          date-month: 'overwriteDemand/month'
          date-year: 'overwriteDemand/year'
          page: 'currentPage'
      # Date year/month + pagination:
      - routePath: '/{date-year}/{date-month}/{page-label}-{page}'
        _controller: 'News::list'
        _arguments:
          date-month: 'overwriteDemand/month'
          date-year: 'overwriteDemand/year'
          page: 'currentPage'
    defaultController: 'News::list'
    defaults:
      page: '0'
      date-month: ''
      date-year: ''
    requirements:
      page: '\d+'
      date-month: '\d+'
      date-year: '\d+'
    aspects:
      news-title:
        type: NewsTitle
      page-label:
        type: LocaleModifier
        default: page
        localeMap:
          -
            locale: 'de_DE.*'
            value: seite
      page:
        type: StaticRangeMapper
        start: '1'
        end: '20'
      date-month:
        type: StaticValueMapper
        map:
          1: '01'
          2: '02'
          3: '03'
          4: '04'
          5: '05'
          6: '06'
          7: '07'
          8: '08'
          9: '09'
          10: '10'
          11: '11'
          12: '12'
        date-year:
          type: StaticRangeMapper
          start: '2000'
          end: '2030'
`
the routing is working fine, but the overwrite of the dateMenu is not working!
<img width="1351" alt="Bildschirmfoto 2023-08-07 um 12 12 38" src="https://github.com/georgringer/news/assets/8898397/adda85e5-99ce-4a2b-95c9-30f9afe6f8b4">
It sticks to the first entries 2023...
Without configuring routing the routing for DateMenu everything works fine...I choose the year and month and the list switch to these news....

**Comment by georgringer** [comment] 2023-09-29 08:11
please try 
```
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
```

istead of 

```
  type: NewsTitle
```

**Comment by trokohl** [comment] 2023-09-29 08:28
this works now but I could swear to have tried that too ... probably with an older version ...

**Comment by georgringer** [comment] 2023-09-29 08:47
i feel the same, maybe test with previous core version - fixed there by accident? ^^

**Comment by georgringer** [comment] 2024-11-05 17:22
closing issue, everything seems to be solved, cleaning up issues

**Closed by georgringer** 2024-11-05 17:22 UTC
