### ISSUE TITLE
Probleme with translation of an article built up with content elements

### ISSUE THREAD

**Issue by WillyRM** [georgringer/news#742] opened 2018-09-25 09:15 UTC
## Bug Report

Hello,

I have built up my news articles using "content elements". When I try to translate this article, the first content element within the article is replaced and linked to any content element on the page.

When I delete this content element, the linked content element is also deleted.

How can I solve the problem? If you need further information, please let me know.

**Environment**
- TYPO3 version(s): 8.7.19
- news version: 7.0.5
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 10

**Comment by friggingee** [comment] 2019-11-26 10:33
Can confirm that this issue exists on T3 8.7.27, tx_news 6.3.0 in composer mode on Linux.
Debugging shows that the DataHandler replaces one of the related content elements with a random ID when translating.
I wasn't able to figure out yet, when and why exactly that happens but right now I'd assume that the issue is most likely related to a core issue with inline elements rather than a tx_news problem.

**Comment by friggingee** [comment] 2019-11-26 12:22
Adding
```
$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['content_elements']['config']['behaviour'] = [
    'localizeChildrenAtParentLocalization' => true,
];
```
seems to resolve the issue.

This might actually be a tx_news issue then, after all.

**Comment by mindpilot** [comment] 2019-11-26 13:43
Same here: TYPO3 8.7.29 width tx_news 6.3.0 or tx_news 7.3.1
Adding 'localizeChildrenAtParentLocalization' => true, as suggested by @friggingee solves the problem.

**Comment by friggingee** [comment] 2019-11-26 14:21
Seems to be closely related to https://forge.typo3.org/issues/57272.

In accordance with the discussion and conclusions from that ticket, I'd say that this is not an EXT:news bug after all because fixing this might break working workarounds in other installations.
Also this core bug seems to be solved in v9.

**Comment by georgringer** [comment] 2024-05-17 06:07
code changed a couple of times, closing issue therefore. feel free to reopen a new one if still relevant

**Closed by georgringer** 2024-05-17 06:07 UTC
