### ISSUE TITLE
Cache with identifier "cache_news_category" does not exist

### ISSUE THREAD

**Issue by buepro** [georgringer/news#917] opened 2019-05-24 13:21 UTC
## Bug Report

**Current Behavior**
The distribution pizpalue depends on the news extension hence it gets installed wehn installing the distribution. During the installation the following error message appears:

```
Oops, an error occurred!
A cache with identifier "cache_news_category" does not exist.
More information regarding this error might be available online.
```
The online link points to [this page](https://wiki.typo3.org/Exception/CMS/1203699034).

**Expected behavior/output**
No error message should come up.

**Environment**
- TYPO3 version(s): 9.5.7
- news version: 7.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux

**Comment by foobar13372** [comment] 2019-07-16 05:37
Duplicate? #869 

Seems to happen quite a lot lately, on 8 and 9 as well...

**Comment by georgringer** [comment] 2021-11-05 09:31
can't reproduce such things on 10 anymore, closing this issue

**Closed by georgringer** 2021-11-05 09:31 UTC
