### ISSUE TITLE
Preview of hidden records only works in default language

### ISSUE THREAD

**Issue by timdreier** [georgringer/news#1521] opened 2021-06-07 10:40 UTC
## Bug Report

**Current Behavior**
Previewing a hidden News record in a non-default language leads to "The news record is not available anymore." using the default configuration:
https://docs.typo3.org/p/georgringer/news/master/en-us/AdministratorManual/BestPractice/PreviewOfRecord/Index.html

**Expected behavior/output**
Previewing a hidden News record in a non-default language previews the News record.

**Environment**
- TYPO3 version(s): 10.4.16
- news version: 8.5.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: OSX 11.3

**Additional context**
The languages are set by /en/, /de/, ...

**Comment by georgringer** [comment] 2022-06-09 18:34
closing as duplicate of https://github.com/georgringer/news/issues/1483

**Closed by georgringer** 2022-06-09 18:34 UTC
