### ISSUE TITLE
Strange error window when trying adding a new tag 

### ISSUE THREAD

**Issue by r4fx** [georgringer/news#282] opened 2017-03-17 20:01 UTC
This error show up when user trying to add a tag to news record that does not currently exist.

The catch is ok, but this message should be shown in nice red message (in the upper right corner) i think.

![zrzut ekranu 2017-03-17 o 20 48 29](https://cloud.githubusercontent.com/assets/4216415/24060563/190c78a6-0b54-11e7-9963-68824870f762.png)

**Comment by georgringer** [comment] 2018-01-23 04:04
closing as duplicate of https://github.com/georgringer/news/issues/184

**Closed by georgringer** 2018-01-23 04:04 UTC
Labels: Confirmed, Task
